-- Erstelle die Tabelle Kunden
CREATE TABLE Kunden (
    KundenID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- KundenID als Primärschlüssel mit IDENTITY
    Name VARCHAR2(100) NOT NULL,              -- Name des Kunden, nicht null
    Stadt VARCHAR2(100) NOT NULL,             -- Stadt des Kunden, nicht null
    Land VARCHAR2(100) NOT NULL                -- Land des Kunden, nicht null
);

-- Erstelle die Tabelle Produkte
CREATE TABLE Produkte (
    ProduktID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ProduktID als Primärschlüssel mit IDENTITY
    Produktname VARCHAR2(100) NOT NULL,        -- Name des Produkts, nicht null
    Preis NUMBER(10, 2) NOT NULL                -- Preis des Produkts mit zwei Dezimalstellen, nicht null
);

-- Erstelle die Tabelle Bestellungen
CREATE TABLE Bestellungen (
    BestellID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- BestellID als Primärschlüssel mit IDENTITY
    KundenID NUMBER,                               -- KundenID zur Verknüpfung mit der Kunden-Tabelle
    Produkt VARCHAR2(100),                         -- Name des bestellten Produkts
    Bestelldatum DATE,                             -- Datum der Bestellung
    Menge NUMBER,                                  -- Menge des bestellten Produkts
    FOREIGN KEY (KundenID) REFERENCES Kunden(KundenID) -- Setze eine Fremdschlüsselbeziehung zu Kunden
);

-- Füge fiktive Daten in die Kunden-Tabelle ein
INSERT INTO Kunden (Name, Stadt, Land) VALUES 
('Max Mustermann', 'Berlin', 'Deutschland'); -- Max Mustermann aus Berlin

INSERT INTO Kunden (Name, Stadt, Land) VALUES 
('Anna Müller', 'Frankfurt', 'Deutschland');  -- Anna Müller aus Frankfurt

INSERT INTO Kunden (Name, Stadt, Land) VALUES 
('John Doe', 'New York', 'USA');              -- John Doe aus New York

INSERT INTO Kunden (Name, Stadt, Land) VALUES 
('Jane Smith', 'London', 'UK');               -- Jane Smith aus London

-- Füge fiktive Daten in die Produkte-Tabelle ein
INSERT INTO Produkte (Produktname, Preis) VALUES 
('Laptop', 999.99);                           -- Produkt: Laptop, Preis: 999,99€

INSERT INTO Produkte (Produktname, Preis) VALUES 
('Smartphone', 499.99);                       -- Produkt: Smartphone, Preis: 499,99€

INSERT INTO Produkte (Produktname, Preis) VALUES 
('Tablet', 299.99);                           -- Produkt: Tablet, Preis: 299,99€

-- Füge fiktive Daten in die Bestellungen-Tabelle ein
INSERT INTO Bestellungen (KundenID, Produkt, Bestelldatum, Menge) VALUES 
(1, 'Laptop', TO_DATE('2024-10-01', 'YYYY-MM-DD'), 1);               -- Max Mustermann bestellt 1 Laptop am 01.10.2024

INSERT INTO Bestellungen (KundenID, Produkt, Bestelldatum, Menge) VALUES 
(2, 'Smartphone', TO_DATE('2024-10-02', 'YYYY-MM-DD'), 2);           -- Anna Müller bestellt 2 Smartphones am 02.10.2024

INSERT INTO Bestellungen (KundenID, Produkt, Bestelldatum, Menge) VALUES 
(1, 'Tablet', TO_DATE('2024-10-03', 'YYYY-MM-DD'), 1);                -- Max Mustermann bestellt 1 Tablet am 03.10.2024

INSERT INTO Bestellungen (KundenID, Produkt, Bestelldatum, Menge) VALUES 
(3, 'Smartphone', TO_DATE('2024-10-04', 'YYYY-MM-DD'), 1);           -- John Doe bestellt 1 Smartphone am 04.10.2024
